version: '3.8'
services:
  wiremock:
    image: wiremock/wiremock:3.13.0-1-alpine
    ports:
      - "8181:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
