version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"   # Expose RabbitMQ's AMQP port
      - "15672:15672" # Expose RabbitMQ's management web interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq # Use a host directory for persistence
    restart: always